kind = "web"
previewPath = "/"
title = "League of Legends"
version = "1.0.0"
id = "artifacts/lol-website"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19438

[services.development]
run = "pnpm --filter @workspace/lol-website run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/lol-website", "run", "build" ]
publicDir = "artifacts/lol-website/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19438"
BASE_PATH = "/"
